#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

VAL_RE = "0x00000000[0-9a-f]+"

@test(0, "pgtbltest")
def test_pgtbltest():
    r.run_qemu(shell_script([
        'pgtbltest'
    ]), timeout=300)

@test(10, "pgtbltest: ugetpid", parent=test_pgtbltest)
def test_ugetpid_():
    r.match('^ugetpid_test: OK$')

@test(10, "pgtbltest: print_kpgtbl", parent=test_pgtbltest)
def test_print_kpgtbl_():
    r.match(
        f'^page table {VAL_RE}$',
        f'^ \\.\\.0: pte {VAL_RE} pa {VAL_RE}$',
        f'^ \\.\\. \\.\\.0: pte {VAL_RE} pa {VAL_RE}$',
        f'^ \\.\\. \\.\\. \\.\\.0: pte {VAL_RE} pa {VAL_RE}$',
        f'^ \\.\\. \\.\\. \\.\\.1: pte {VAL_RE} pa {VAL_RE}$',
        f'^ \\.\\. \\.\\. \\.\\.2: pte {VAL_RE} pa {VAL_RE}$',
        f'^ \\.\\. \\.\\. \\.\\.3: pte {VAL_RE} pa {VAL_RE}$',
        f'^ \\.\\.255: pte {VAL_RE} pa {VAL_RE}$',
        f'^ \\.\\. \\.\\.511: pte {VAL_RE} pa {VAL_RE}$',
        f'^ \\.\\. \\.\\. \\.\\.509: pte {VAL_RE} pa {VAL_RE}$',
        f'^ \\.\\. \\.\\. \\.\\.510: pte {VAL_RE} pa {VAL_RE}$',
        f'^ \\.\\. \\.\\. \\.\\.511: pte {VAL_RE} pa {VAL_RE}$',
    )

@test(10, "pgtbltest: pgaccess", parent=test_pgtbltest)
def test_pgaccess_():
    r.match('^pgaccess_test: OK$')

@test(5, "answers-pgtbl.txt")
def test_answers():
    # just a simple sanity check, will be graded manually
    check_answers("answers-pgtbl.txt")

@test(0, "usertests")
def test_usertests():
    r.run_qemu(shell_script([
        'usertests -q'
    ]), timeout=300)

@test(10, "usertests: all tests", parent=test_usertests)
def test_usertests():
    r.match('^ALL TESTS PASSED$')

@test(1, "time")
def test_time():
    check_time()

run_tests()
